package com.awesomepetprojects.movieaday.utils

const val MOVIE_DB_API_KEY = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzZjMxNmU5ODJkNmVkNWY0ZjQ1ZjJkMWE4ZTdhYWVmOSIsInN1YiI6IjY1YzUyNjdkMWI3MGFlMDE4NGEyMjYzZiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.G8cp1IiPUz9Irna3KsN3Vbn3TVcLWZerLoLjSvEzO0Y"
const val BASE_URL = "https://api.themoviedb.org/3/"
const val DATABASE_NAME = "database"